# Generated by Django 3.2.15 on 2022-10-12 14:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
