# Generated by Django 3.2.15 on 2022-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_header_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='comment_mode',
            field=models.CharField(choices=[('OFF', 'Off'), ('MOD', 'Moderated'), ('AA', 'Auto-Approve')], default='MOD', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=30, unique=True),
        ),
    ]
