# Generated by Django 3.2.15 on 2022-10-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20221023_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_mode',
            field=models.CharField(choices=[('OFF', 'Off'), ('MOD', 'Moderated'), ('AAC', 'Auto-Approve')], default='MOD', max_length=3),
        ),
    ]
