# Generated by Django 3.2.15 on 2022-10-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_comment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_mode',
            field=models.CharField(choices=[('OFF', 'Off'), ('MOD', 'Moderated'), ('AAC', 'Auto-Approve')], default='AAC', max_length=3),
        ),
    ]
