# Generated by Django 3.2.15 on 2022-10-24 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0011_commentreaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('user', 'comment')},
        ),
    ]
