# Generated by Django 3.2.15 on 2022-10-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_commentreaction_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.DeleteModel(
            name='CommentReaction',
        ),
    ]
